# The URL the site will be built for
base_url = "https://www.blog.khrynczenko.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "Krzysztof Hrynczenko's Dev Diary"
description = "My little place where I write about things that interest me."

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
# Put all your custom variables here
